// <auto-generated />
using System;
using CruiseCompany.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TripAPI.Migrations
{
    [DbContext(typeof(CruiseDbContext))]
    partial class CruiseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CruiseCompany.Models.CruiseRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CruiseRoutes");
                });

            modelBuilder.Entity("CruiseCompany.Models.Liner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Liners");
                });

            modelBuilder.Entity("CruiseCompany.Models.RouteLiner", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("LinerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Season")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId", "LinerId");

                    b.HasIndex("LinerId");

                    b.ToTable("RouteLiners");
                });

            modelBuilder.Entity("CruiseCompany.Models.RouteLiner", b =>
                {
                    b.HasOne("CruiseCompany.Models.Liner", "Liner")
                        .WithMany("RouteLiners")
                        .HasForeignKey("LinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CruiseCompany.Models.CruiseRoute", "Route")
                        .WithMany("RouteLiners")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liner");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CruiseCompany.Models.CruiseRoute", b =>
                {
                    b.Navigation("RouteLiners");
                });

            modelBuilder.Entity("CruiseCompany.Models.Liner", b =>
                {
                    b.Navigation("RouteLiners");
                });
#pragma warning restore 612, 618
        }
    }
}
