version: "3.9"

services:
  flask_lab_3:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    depends_on:
      - dnmonster
      - redis
    networks:
      - backend

  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

networks:
  backend:
    driver: bridge
