# Следует иметь ввиду, что docker-compose работает с сервисами. 
# 1 сервис = 1 контейнер. 
# Сервисом может быть клиент, сервер, сервер баз данных и т. д. 
# Раздел, в котором будут описаны 
# сервисы, начинается с 'services'
services:
    # Первый сервис (и единственный в данном примере) 
    #  мы назовем identidock
    identidock:
        # Ключевое слово "build" позволяет задать
        # путь к файлу Dockerfile, который нужно 
        # использовать для создания 
        # образа, который позволит запустить сервис.
        # Здесь '.' соответствует пути к папке сервера,
        # которая содержит соответствующий Dockerfile
        build: .
        
        # ключевое слово ports аналогично 
        # флагу -p у команды docker run
        # При его использовании применяется следующая 
        # конструкция: [порт компьютера]:[порт контейнера]
        # В нашем случае будем, как и ранее, использовать 
        # порт компьютера 5000
        # и организуем его связь с портом 5000 контейнера
        ports:
            -  5000:5000
        # ключевое слово environment аналогично 
        # флагу -e у команды docker run
        # т. е. мы устанавливаем переменные среды у контейнера
        environment:
            ENV: DEV
        # ключевое слово volumes аналогично 
        # флагу -v команды docker run
        # т. е. мы привязываем директорию ./app 
        # на хосте (наш компьютер)
        # к директории /app в контейнере
        volumes:
            - ./app:/app

